blank_issues_enabled: false
contact_links:
  - name: General Research Inquiries
    url: https://simovi.ucr.ac.cr/
    about: For questions about our research projects, collaborations, or academic inquiries, please visit our contact page.
  - name: Request a New Feature
    url: https://github.com/simovilab/.github/discussions
    about: For proposing new features or enhancements, please use our Discussions forum.
  - name: Data Access or Privacy Concerns
    url: mailto:simovi@ucr.ac.cr
    about: For questions about data access, privacy, or ethical use, contact our data team.
